version: "3.8"

networks:
  spring-mongo-net:
    driver: bridge
services:
  mongo:
    image: mongo:latest
    container_name: json-difference-mongodb
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      - spring-mongo-net
  json-difference-api:
    build: .
    container_name: json-difference-api
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=jsonbase64db
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net